'use client';

import { useState } from 'react';
import { FunnelIcon } from '@heroicons/react/24/outline';
import { Card, CardHeader, CardContent, CardFooter } from '@/components';

export default function ReportFilters() {
  const [filters, setFilters] = useState({
    type: '',
    dateRange: '',
    generatedBy: '',
    search: '',
  });

  const handleFilterChange = (key: string, value: string) => {
    setFilters(prev => ({
      ...prev,
      [key]: value,
    }));
  };

  return (
    <Card>
      <CardHeader 
        title="Report Filters"
        icon={<FunnelIcon className="h-5 w-5 text-gray-400" />}
      />
      
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {/* Search */}
          <div>
            <label htmlFor="search" className="block text-sm font-medium text-gray-700">
              Search
            </label>
            <input
              type="text"
              id="search"
              className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Search reports..."
              value={filters.search}
              onChange={(e) => handleFilterChange('search', e.target.value)}
            />
          </div>

          {/* Report Type Filter */}
          <div>
            <label htmlFor="type" className="block text-sm font-medium text-gray-700">
              Report Type
            </label>
            <select
              id="type"
              className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              value={filters.type}
              onChange={(e) => handleFilterChange('type', e.target.value)}
            >
              <option value="">All Types</option>
              <option value="Compliance Summary">Compliance Summary</option>
              <option value="Risk Assessment">Risk Assessment</option>
              <option value="Audit Report">Audit Report</option>
              <option value="Incident Report">Incident Report</option>
              <option value="Training Report">Training Report</option>
            </select>
          </div>

          {/* Date Range Filter */}
          <div>
            <label htmlFor="dateRange" className="block text-sm font-medium text-gray-700">
              Date Range
            </label>
            <select
              id="dateRange"
              className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              value={filters.dateRange}
              onChange={(e) => handleFilterChange('dateRange', e.target.value)}
            >
              <option value="">All Time</option>
              <option value="last7days">Last 7 days</option>
              <option value="last30days">Last 30 days</option>
              <option value="last90days">Last 90 days</option>
              <option value="thisYear">This Year</option>
              <option value="lastYear">Last Year</option>
            </select>
          </div>

          {/* Generated By Filter */}
          <div>
            <label htmlFor="generatedBy" className="block text-sm font-medium text-gray-700">
              Generated By
            </label>
            <select
              id="generatedBy"
              className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              value={filters.generatedBy}
              onChange={(e) => handleFilterChange('generatedBy', e.target.value)}
            >
              <option value="">All Users</option>
              <option value="John Smith">John Smith</option>
              <option value="Jane Doe">Jane Doe</option>
              <option value="Mike Johnson">Mike Johnson</option>
              <option value="Sarah Wilson">Sarah Wilson</option>
            </select>
          </div>
        </div>
      </CardContent>

      <CardFooter>
        <div className="flex justify-end">
          <button
            type="button"
            className="text-sm text-gray-500 hover:text-gray-700"
            onClick={() => setFilters({ type: '', dateRange: '', generatedBy: '', search: '' })}
          >
            Clear all filters
          </button>
        </div>
      </CardFooter>
    </Card>
  );
}
