'use client';

import { ReactNode } from 'react';
import { 
  DocumentTextIcon,
  CalendarIcon,
  UserIcon,
  ArrowDownTrayIcon
} from '@heroicons/react/24/outline';
import { Card, CardHeader, CardContent, CardFooter } from './Card';
import { cn } from '../../lib/utils';

interface ReportCardProps {
  id: string | number;
  title: string;
  type: string;
  generatedBy: string;
  generatedDate: string;
  status: 'Completed' | 'In Progress' | 'Failed';
  downloadUrl?: string;
  className?: string;
  onClick?: () => void;
  actions?: ReactNode;
}

const ReportCard = ({
  id,
  title,
  type,
  generatedBy,
  generatedDate,
  status,
  downloadUrl,
  className,
  onClick,
  actions,
}: ReportCardProps) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Completed':
        return 'text-green-600 bg-green-100 border-green-200';
      case 'In Progress':
        return 'text-yellow-600 bg-yellow-100 border-yellow-200';
      case 'Failed':
        return 'text-red-600 bg-red-100 border-red-200';
      default:
        return 'text-gray-600 bg-gray-100 border-gray-200';
    }
  };

  return (
    <Card 
      className={cn('h-full', className)}
      clickable={!!onClick}
      onClick={onClick}
    >
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="flex items-center space-x-3">
            <div className="flex-shrink-0">
              <DocumentTextIcon className="h-8 w-8 text-gray-400" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-900">
                {title}
              </h3>
              <p className="text-sm text-gray-500">{type}</p>
            </div>
          </div>
          <span className={cn(
            'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border',
            getStatusColor(status)
          )}>
            {status}
          </span>
        </div>
      </CardHeader>

      <CardContent>
        <div className="space-y-3">
          <div className="flex items-center text-sm text-gray-500">
            <UserIcon className="h-4 w-4 mr-2" />
            <span>Generated by: {generatedBy}</span>
          </div>

          <div className="flex items-center text-sm text-gray-500">
            <CalendarIcon className="h-4 w-4 mr-2" />
            <span>Date: {generatedDate}</span>
          </div>
        </div>
      </CardContent>

      <CardFooter>
        <div className="flex justify-between items-center w-full">
          {downloadUrl && (
            <a
              href={downloadUrl}
              className="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            >
              <ArrowDownTrayIcon className="h-4 w-4 mr-1" />
              Download
            </a>
          )}
          {actions}
        </div>
      </CardFooter>
    </Card>
  );
};

export default ReportCard;
